name: Jake Burdess
favicon: null
layout_spectrum: 0.74842
typography_spectrum: 0.14354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#475057'
    - '#000000'
    - '#7b8793'
    - '#a3acb5'
    - '#c3c8ce'
  brandStrength: 0.7957959359046072
  lightness: 0.15974593488499522
  saturation: 0.40799775905907154
  rhythmicContrast: 0.09467134508304298
purpose: []
